# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0005_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_being_add',
            field=models.BooleanField(default=False),
        ),
    ]
