# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post_set',
            field=models.ManyToManyField(to='wpsblog.Post'),
        ),
    ]
