# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0013_auto_20170227_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
