# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0015_auto_20170301_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
